#
# production settings
# 
# (version: 30, saved: 2022-04-23 22:14:51)
#
---
production:
  settings:
    id: trial7
    caption: Langeness
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 1409
    strings-idstart: 420
    version: 30
