#
# production settings
# 
# (version: 21, saved: 2022-04-22 17:23:19)
#
---
production:
  settings:
    id: trial7
    caption: Langeness
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 1409
    strings-idstart: 420
    version: 21
