#
# production settings
# 
# (version: 30, saved: 2022-05-03 19:45:16)
#
---
production:
  settings:
    id: trial8
    caption: "Demon's Souls"
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 1410
    strings-idstart: 520
    version: 30
