#
# production settings
# 
# (version: 97, saved: 2022-05-18 00:15:07)
#
---
production:
  settings:
    id: trial8
    caption: "Demon's Souls"
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 1410
    strings-idstart: 0
    version: 97
