#
# production settings
# 
# (version: 51, saved: 2022-05-14 22:45:27)
#
---
production:
  settings:
    id: trial8
    caption: "Demon's Souls"
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 1410
    strings-idstart: 0
    version: 51
